Repository jincde/Chicken-Kurly, pull requests merged in 2022-11, with the labels that each got.

#2 feat : products model 생성
  PJT/urls.py
  products/migrations/0001_initial.py
  products/migrations/0002_auto_20221110_1057.py
  products/models.py
  products/urls.py
Labels: BE, feature

#3 chore(urls) : 프로젝트 urls
  PJT/urls.py
Labels: BE, chore

#4 feat : product 판매 상품 등록 및 index에서 보여주기
  images/business-man.png
  images/business-man_JUwSEL7.png
  images/bussiness-man.png
  images/bussiness-man_9vVcZpF.png
  images/logo_test.png
  images/logo_test_ePVJNJa.png
  images/밍이.jpg
  images/빵.ico
  products/admin.py
  products/forms.py
  products/templates/products/create.html
  products/templates/products/index.html
  products/urls.py
  products/views.py
Labels: BE, feature

#5 style : 내비게이션 바
  PJT/urls.py
  products/templates/products/index.html
  static/css/style.css
  static/images/logo.png
  templates/base.html
Labels: FE, style, chore

#7 Dh 01 - articles app CRUD 구현 완료
  .gitignore
  PJT/settings.py
  PJT/urls.py
  accounts/migrations/0001_initial.py
  accounts/models.py
  articles/forms.py
  articles/migrations/0001_initial.py
  articles/models.py
  articles/templates/articles/create.html
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  articles/templates/articles/update.html
  articles/urls.py
  articles/views.py
Labels: BE, done

#8 feat(products/index) : products 인덱스 페이지 전체 구조 완성
  products/templates/products/index.html
  static/css/style.css
  templates/base.html
Labels: FE, done, style

#11 docs: profile/profile_update 수정
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/profile_update.html
Labels: BE, docs

#12 fix : products 장바구니 & 찜 Null 오류 수정
  PJT/urls.py
  accounts/templates/accounts/login.html
  accounts/views.py
  products/admin.py
  products/templates/products/detail.html
  products/templates/products/index.html
  products/urls.py
  products/views.py
Labels: BE, fix

#13 feat : 회원가입/로그인 사이트 연결, carousel 광고 추가
  accounts/templates/accounts/login.html
  products/templates/products/index.html
  static/css/style.css
  templates/base.html
Labels: FE, feature, style, chore

#14 feat : article 댓글 작성 및 삭제 기능 구현
  articles/models.py
  articles/templates/articles/index.html
  articles/urls.py
  articles/views.py
Labels: BE, feature

#15 chore: signup&login 수정
  PJT/settings.py
  PJT/urls.py
  accounts/templates/accounts/login.html
  accounts/views.py
  templates/base.html
Labels: BE, chore

#17 chore(base) : footer 고객센터 작성
  templates/base.html
Labels: chore

#18 feat(products) : 상품 정보 수정 및 비로그인 유저 상품 조회 시 오류 수정
  products/templates/products/create.html
  products/templates/products/detail.html
  products/templates/products/index.html
  products/urls.py
  products/views.py
Labels: BE, feature, chore

#19 style : 회원가입 폼 디자인
  accounts/templates/accounts/signup.html
  static/css/style.css
  static/images/carousel1.jpg
  static/images/carousel2.jpg
  static/images/logo2.png
  templates/base.html
Labels: done, style, chore

#20 style : 로그인 폼 스타일
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  static/css/style.css
  templates/base.html
Labels: FE, done, style, chore

#21 fix : 디자인 폼 데이터 안넘어가는 이슈 수정
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
Labels: fix, chore

#22 docs(README) : README 문서 작성
  README.assets/carousel1.jpg
  README.assets/carousel2.jpg
  README.md
Labels: docs

#23 style : products 카드 디자인 및 구조 스타일
  images/images/CK_logo_Purple.jpg
  products/templates/products/index.html
  static/css/style.css
  templates/base.html
Labels: done, style, chore

#24 feat(products) : 상품 문의 & 답변 기능 추가
  products/forms.py
  products/models.py
  products/templates/products/detail.html
  products/urls.py
  products/views.py
Labels: BE, feature

#25 feat : 상품 후기 작성 기능 추가
  accounts/models.py
  images/KakaoTalk_20221106_152232794_01.jpg
  images/KakaoTalk_20221106_152232794_02.jpg
  images/KakaoTalk_20221106_152232794_03.jpg
  products/forms.py
  products/models.py
  products/templates/products/detail.html
  products/templates/products/index.html
  products/templates/products/review.html
  products/urls.py
  products/views.py
Labels: BE, feature

#26 chore: 회원정보
  accounts/models.py
  accounts/templates/accounts/profile.html
  accounts/views.py
Labels: BE, chore

#29 style : product 디테일 페이지 스타일
  products/templates/products/detail.html
Labels: style, chore

#30 chore : product 찜 별 아이콘으로 변경(주석)
  products/templates/products/detail.html
Labels: chore

#31 style : article 좋아요 비동기 구현
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  articles/views.py
  images/KakaoTalk_20221106_152232794_01.jpg
  images/KakaoTalk_20221106_152232794_02.jpg
  images/KakaoTalk_20221106_152232794_03.jpg
Labels: BE, style

#32 feat : 상품 후기 수정 기능 추가
  products/models.py
  products/templates/products/detail.html
  products/templates/products/review.html
  products/views.py
Labels: BE, feature

#35 fix : 찾을 수 없는 필드 수정
  accounts/migrations/0001_initial.py
  articles/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/templates/products/index.html
Labels: fix

#36 chore: 회원정보 수정
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/templates/accounts/profile.html
  products/migrations/0001_initial.py
Labels: BE, chore

#37 feat(index) : 상품 swiper 기능 구현
  products/templates/products/index.html
  static/css/style.css
  templates/base.html
Labels: FE, done, feature, style

#38 style : 내비게이션 바 상세 디자인
  accounts/migrations/0001_initial.py
  products/migrations/0001_initial.py
  static/css/style.css
  templates/base.html
Labels: FE, done, style, chore

#40 feat(products) : 상품 후기 이미지 제외하고 구현 완료
  accounts/migrations/0001_initial.py
  articles/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/templates/products/detail.html
  products/templates/products/review.html
  products/urls.py
  products/views.py
Labels: BE, feature

#43 feat : accounts/detail 스타일
  accounts/templates/accounts/profile.html
  static/css/style.css
  templates/base.html
Labels: FE, done, feature, style

#44 docs(README) : 차화영님 깃허브 링크 오류 수정
  README.md
Labels: docs, chore

#47 style : 회원정보 대시보드
  accounts/templates/accounts/profile.html
Labels: style, chore

#48 fix : 대시보드 무너짐 수정
  accounts/templates/accounts/profile.html
Labels: fix

#49 fix(products) : 문의 수정 시 필드에 값 제대로 들어가도록 수정
  products/templates/products/detail.html
Labels: BE, done, fix, style

#50 style : 회원가입 폼 웨이브 요소 추가
  accounts/templates/accounts/signup.html
  images/images/CK_logo_Purple_RkqwiBe.jpg
  static/css/style.css
Labels: FE, done, style, chore

#52 feat(products) 상품 후기 이미지 보이도록 함
  products/templates/products/detail.html
  products/views.py
  static/css/products/review.css
Labels: BE, feature

#55 fix : articles 자유게시판 좋아요 비동기 버그 수정완료
  PJT/settings.py
  accounts/migrations/0001_initial.py
  articles/migrations/0001_initial.py
  articles/templates/articles/index.html
  articles/views.py
  products/migrations/0001_initial.py
Labels: BE, fix

#53 style : 문의 제목 hover시 커서 모양 변경
  products/templates/products/detail.html
  static/css/style.css
Labels: style, chore

#56 fix : 후기 무너짐 해결
  products/templates/products/detail.html
Labels: fix

#57 feature : articles app 자유게시판 상세페이지 댓글 페이지네이션 기능 구현 완료
  articles/models.py
  articles/templates/articles/create.html
  articles/templates/articles/detail.html
  articles/views.py
  templates/base.html
Labels: BE, feature

#58 style : 상품 디테일 페이지 후기/문의 스타일
  products/templates/products/detail.html
Labels: FE, style

#59 fix : articles app 자유게시판 좋아요 버튼 버그 수정 및 자잘한 코드수정
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  articles/views.py
Labels: FE, BE, fix, style

#60 feat : 하단 내비게이션 바 추가
  accounts/templates/accounts/login.html
  products/templates/products/detail.html
  templates/base.html
Labels: FE, feature, style

#61 feat(products) : 상품 찜 비동기 구현 완료
  products/templates/products/detail.html
  products/views.py
  static/css/products/review.css
Labels: BE, done, feature

#64 style : 리뷰 작성 폼 디자인
  products/templates/products/review.html
Labels: style

#63 chore: accounts-profile-imageupload
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/templates/accounts/create.html
  accounts/templates/accounts/profile.html
  accounts/views.py
  articles/migrations/0001_initial.py
  products/migrations/0001_initial.py
Labels: BE, chore

#65 style : 리뷰 작성 폼 웨이브 추가
  products/templates/products/review.html
Labels: style

#67 test : 커밋 메세지
  accounts/migrations/0001_initial.py
  articles/migrations/0001_initial.py
  products/migrations/0001_initial.py
Labels: help

#68 chore: 회원정보 수정
  accounts/migrations/0001_initial.py
  accounts/templates/accounts/profile.html
  articles/migrations/0001_initial.py
  products/migrations/0001_initial.py
Labels: BE, chore

#69 feat : 인스타그램 피드 불러오기
  products/templates/products/index.html
Labels: FE, done, feature

#71 chore : favicon 추가, README 수정
  README.md
  static/images/android-icon-36x36.png
  static/images/android-icon-72x72.png
  templates/base.html
Labels: docs, chore

#72 chore: 회원정보 수정
  accounts/admin.py
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/profile_update.html
  accounts/views.py
  articles/migrations/0001_initial.py
  products/migrations/0001_initial.py
Labels: BE, chore

#73 feat : accounts 프로필에서 찜한 목록 불러오기 구현
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/templates/accounts/profile.html
  accounts/views.py
  articles/migrations/0001_initial.py
  images/images/운동.jpg
  products/migrations/0001_initial.py
Labels: BE, feature

#74 chore : 컨트리뷰터 링크 수정
  README.md
Labels: docs, chore

#75 chore : accounts앱 views.py Product 모델 import 코드 추가
  accounts/migrations/0001_initial.py
  accounts/views.py
  products/migrations/0001_initial.py
Labels: BE, chore

#76 chore: 회원정보[작성한 글 수정]
  accounts/migrations/0001_initial.py
  accounts/templates/accounts/profile.html
  articles/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/views.py
Labels: BE, chore

#77 Dh 09 'feature : articles app 자유게시판 댓글 좋아요 기능, 대댓글 기능'
  PJT/settings.py
  articles/forms.py
  articles/models.py
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  articles/urls.py
  articles/views.py
Labels: BE, feature, chore

#79 feat : accounts앱 찜한 상품 삭제 구현
  accounts/templates/accounts/profile.html
  accounts/urls.py
  accounts/views.py
  products/views.py
Labels: BE, feature

#78 style : articles 인덱스 디자인
  README.md
  accounts/migrations/0001_initial.py
  articles/templates/articles/create.html
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  products/templates/products/create.html
  products/templates/products/review.html
  static/css/style.css
Labels: FE, style, help

#81 style : articles 인덱스 페이지 디자인
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  articles/views.py
  templates/base.html
Labels: FE, style

#82 feat : 내비게이션 바 로그인/아웃 분기 추가
  accounts/migrations/0001_initial.py
  articles/migrations/0001_initial.py
  products/migrations/0001_initial.py
  templates/base.html
Labels: FE, feature

#85 fix(accounts) : 장바구니 템플릿 불필요한 코드 제거 및 view 오류 수정
  accounts/templates/accounts/cart.html
  accounts/urls.py
  accounts/views.py
Labels: BE, fix, chore, refactor

#86 feat : like animation
  articles/templates/articles/index.html
  products/templates/products/index.html
  static/css/style.css
Labels: FE, done, style

#87 fix : contentcard hover 해제 시 부자연스러운 동작 개선
  static/css/style.css
Labels: FE, fix

#88 feat: 회원정보(문의한 글)
  accounts/migrations/0001_initial.py
  accounts/templates/accounts/profile.html
  accounts/views.py
  articles/migrations/0001_initial.py
  products/migrations/0001_initial.py
Labels: BE, feature

#89 chore : 광고 추가
  products/templates/products/index.html
  static/images/carousel3.jpg
  static/images/thin3.jpg
Labels: chore

#90 feat : 검색기능 구현
  articles/templates/articles/search.html
  articles/urls.py
  articles/views.py
  templates/base.html
Labels: BE, feature

#91 style : 검색 결과 페이지 디자인
  articles/templates/articles/search.html
  articles/views.py
Labels: FE, done, style

#92 feat : product 인덱스 판매량 정렬, 조회순 정렬 기능 추가
  products/templates/products/index.html
  products/views.py
Labels: BE, feature

#93 chore: 개인정보 form 수정
  accounts/forms.py
  accounts/templates/accounts/change_password.html
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/profile_update.html
  accounts/views.py
Labels: BE, chore

#94 feature : article app 자유게시판 대댓글 기능 구현
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  articles/templates/articles/recomment.html
  articles/urls.py
  articles/views.py
Labels: BE, feature

#95 chore : 상세 문구 추가
  accounts/templates/accounts/profile.html
  products/templates/products/index.html
Labels: chore

#98 feat : 카카오 도로명주소API 활용, 회원가입시 주소입력 추가
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/templates/accounts/signup.html
  articles/migrations/0001_initial.py
  products/migrations/0001_initial.py
Labels: FE, BE, done, feature

#100 feat : 로그인 오류 시 메세지 출력 기능 구현
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  accounts/views.py
  static/css/style.css
  templates/base.html
Labels: FE, done, feature

#106 feat : 상담원 연결 API 추가
  templates/base.html
Labels: done, feature

#105 feat : 찜한 상품 장바구니 담는 모달에서 수량-금액 변동 & 상품 후기 페이지네이션
  accounts/forms.py
  accounts/templates/accounts/profile.html
  accounts/views.py
  products/templates/products/detail.html
  products/views.py
  static/css/style.css
  static/js/ddibtocart.js
  templates/base.html
Labels: FE, BE, feature

#108 chore : articles app 글 수정,삭제 기능 위치 상세페이지로 이동
  accounts/migrations/0001_initial.py
  articles/migrations/0001_initial.py
  articles/templates/articles/detail.html
  articles/views.py
  products/migrations/0001_initial.py
Labels: BE, chore

#107 chore : accounts 프로필 div 정렬
  accounts/templates/accounts/profile.html
Labels: chore

#110 feat : 아이디 중복 체크 및 username 모델 수정
  accounts/forms.py
  accounts/models.py
  accounts/templates/accounts/signup.html
  accounts/urls.py
  accounts/views.py
  templates/base.html
Labels: FE, BE, done, feature

#111 fix : 아이디 최대길이 지정, 최소길이 오류 수정
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/templates/accounts/signup.html
  articles/migrations/0001_initial.py
  products/migrations/0001_initial.py
Labels: fix

#113 Dh 13 'chore : 자잘한 코드 수정'
  articles/templates/articles/detail.html
  articles/templates/articles/recomment.html
  articles/urls.py
  articles/views.py
Labels: BE, chore

#115 feat(accounts) : 찜한 상품 수량 선택 후 장바구니 담기 버튼 클릭 => 장바구니로 DB 전달
  PJT/settings.py
  accounts/migrations/0001_initial.py
  accounts/templates/accounts/index.html
  accounts/templates/accounts/login.html
  accounts/templates/accounts/profile.html
  accounts/urls.py
  accounts/views.py
  products/forms.py
  products/migrations/0001_initial.py
  products/models.py
  products/templates/products/detail.html
  products/views.py
  static/js/product_inquiries.js
  static/js/sns.js
  templates/base.html
Labels: FE, BE, feature, style

#116 style : accounts index페이지 텍스트 수정
  accounts/templates/accounts/index.html
Labels: FE, style

#118 chore: 회원정보[등급] 수정
  accounts/models.py
  accounts/templates/accounts/profile.html
  accounts/views.py
Labels: BE, chore

#119 chore: 회원정보[등급] 수정
  accounts/admin.py
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/views.py
  articles/migrations/0001_initial.py
  products/migrations/0001_initial.py
Labels: BE, chore

#120 chore: Django[admin]-username 수정
  accounts/models.py
Labels: BE, chore

#121 feat: user model[admin] 등록
  accounts/admin.py
Labels: BE, feature, chore

#122 fix: signup
  accounts/models.py
Labels: BE, fix

#123 fix: 회원정보[등급]
  accounts/templates/accounts/profile.html
Labels: BE, fix

#124 chore: profile[ranking]
  accounts/templates/accounts/profile.html
Labels: BE, chore

#125 refactor: accounts[form]
  accounts/templates/accounts/create.html
  accounts/templates/accounts/profile.html
  accounts/urls.py
Labels: BE, refactor

#126 feat : 찜한 상품 모달 - 장바구니 상황에 따라 수량 누적 기능 구현
  accounts/migrations/0001_initial.py
  accounts/templates/accounts/profile.html
  accounts/views.py
  products/migrations/0001_initial.py
  templates/base.html
Labels: BE, done, feature

#127 fix : 데일리 스크럼때 이슈되었던 버그 수정
  accounts/migrations/0001_initial.py
  accounts/models.py
  articles/migrations/0001_initial.py
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  articles/templates/articles/recomment.html
  articles/views.py
  products/migrations/0001_initial.py
Labels: BE, fix

#128 style : accounts 프로필에서 찜한 상품 모달 클릭 시 요소 간 간격 조정
  accounts/migrations/0001_initial.py
  accounts/templates/accounts/profile.html
  products/migrations/0001_initial.py
Labels: FE, style

#129 refactor : instagram 이슈 수정
  accounts/migrations/__init__.py
  articles/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/templates/products/index.html
Labels: done, refactor

#130 style : articles update페이지 디자인 수정
  articles/templates/articles/update.html
Labels: FE, style

#131 chore : articles app 댓글 좋아요 기능 비동기로 수정
  accounts/migrations/0001_initial.py
  articles/migrations/0001_initial.py
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  articles/templates/articles/recomment.html
  articles/urls.py
  articles/views.py
  products/migrations/0001_initial.py
Labels: BE, chore

#132 chore: 회원정보[order model]
  accounts/models.py
  accounts/templates/accounts/profile.html
  accounts/urls.py
  accounts/views.py
Labels: BE, chore

#133 refactor : 인스타그램 ACCESS_TOKEN 환경변수로 분리, long-lived token으로 교체
  articles/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/templates/products/index.html
  products/views.py
Labels: BE, done, refactor

#135 style : accounts 회원정보 수정 디자인
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/templates/accounts/profile_update.html
  articles/migrations/0001_initial.py
  articles/templates/articles/update.html
  products/migrations/0001_initial.py
Labels: FE, style

#136 fix : 코드수정
  accounts/admin.py
  accounts/templates/accounts/cart.html
  accounts/views.py
  articles/migrations/0001_initial.py
  products/migrations/0001_initial.py
Labels: chore

#143 style: product detail 페이지 스타일 추가
  PJT/settings.py
  products/templates/products/detail.html
  static/css/style.css
  templates/base.html
Labels: FE, style

#147 style : products 찜한 상품 모달 디자인 수정
  accounts/migrations/0001_initial.py
  accounts/templates/accounts/profile.html
  accounts/views.py
  articles/migrations/0001_initial.py
  articles/views.py
  products/migrations/0001_initial.py
Labels: FE, style

#153 style : articles detail 페이지 디자인
  accounts/views.py
  articles/templates/articles/detail.html
  articles/templatetags/filter.py
  articles/views.py
  products/templates/products/index.html
  requirements.txt
  static/css/style.css
  templates/base.html
Labels: style

#156 fix: django social share
  PJT/settings.py
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/templates/accounts/profile_update.html
  articles/migrations/0001_initial.py
  products/migrations/0001_initial.py
  requirements.txt
Labels: BE, fix

#157 done: profile[등급]
  accounts/templates/accounts/profile.html
Labels: BE, done

#158 fix: profile[이미지 정렬]
  accounts/migrations/0001_initial.py
  accounts/templates/accounts/profile.html
  articles/migrations/0001_initial.py
  products/migrations/0001_initial.py
Labels: BE, fix

#159 feat : articles detail 스타일 적용
  articles/templates/articles/detail.html
  static/css/style.css
Labels: FE, done, feature, style

#160 style: base[footer] design
  static/css/footer.css
  static/js/footer.js
  templates/base.html
Labels: FE, style

#161 style : 댓글 섹션 스타일
  articles/templates/articles/detail.html
Labels: style

#162 fix: footer.js
  static/js/footer.js
Labels: FE, fix

#163 feat : 카테고리 불러오기
  products/templates/products/detail.html
  products/templates/products/index.html
  products/views.py
Labels: BE, feature

#164 chore: base[footer]
  static/css/style.css
  templates/base.html
Labels: FE, chore

#167 style : design update
  accounts/templates/accounts/cart.html
  accounts/templates/accounts/profile.html
  articles/templates/articles/detail.html
  products/templates/products/detail.html
Labels: FE, BE, fix, style

#168 style : accounts 프로필 페이지 찜한 상품의 삭제 버튼 icon으로 변경
  accounts/templates/accounts/profile.html
Labels: FE, style

#169 feat : 카테고리 필터기능 추가
  products/templates/products/index.html
  products/views.py
  static/css/style.css
Labels: FE, BE, done, feature

#170 style: products index 스타일
  products/templates/products/index.html
Labels: FE, style

#171 fix : 카테고리 필터링 안되는 오류 수정
  products/templates/products/index.html
  static/css/style.css
Labels: fix

#174 fix : 모달 에러 수정
  accounts/templates/accounts/cart.html
  accounts/templates/accounts/profile.html
  accounts/views.py
  articles/templates/articles/detail.html
  products/models.py
  products/templates/products/detail.html
  products/templates/products/index.html
Labels: fix

#176 style : 세세한 디자인 수정, 광고 배너 추가
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  articles/templates/articles/search.html
  products/templates/products/index.html
  static/images/carousel4.avif
  static/images/carousel5.avif
  static/images/carousel6.avif
  static/images/carousel7.avif
  static/images/carousel8.avif
  static/js/footer.js
  templates/base.html
Labels: style

#177 style : articles 대댓글 상세 페이지 디자인
  accounts/templates/accounts/profile.html
  articles/forms.py
  articles/templates/articles/recomment.html
  articles/views.py
  images/android-icon-72x72.png
Labels: FE, fix, style, refactor

#178 chore: base 수정
  static/js/footer.js
  templates/base.html
Labels: FE, chore

#179 chore: base[footer]
  templates/base.html
Labels: FE, chore

#180 chore: base[footer]
  templates/base.html
Labels: FE, chore

#182 chore: base[footer]
  templates/base.html
Labels: FE, chore

#183 chore : 아티클 대댓글 페이지 프로필 사진 url 연결
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/profile_update.html
  articles/templates/articles/detail.html
  articles/templates/articles/recomment.html
  images/images/android-icon-72x72.png
  static/css/style.css
Labels: chore

#184 style : 세세한 디자인 변경
  accounts/views.py
  articles/templates/articles/detail.html
  products/models.py
  products/templates/products/index.html
  static/images/logo3.png
  templates/article_base.html
  templates/base.html
Labels: style, chore

#186 style : footer 수정
  articles/templates/articles/detail.html
  templates/article_base.html
  templates/base.html
Labels: style

#187 fix : articles 프로필 이미지 url 오류 해결
  accounts/migrations/0001_initial.py
  accounts/templates/accounts/profile_update.html
  articles/migrations/0001_initial.py
  articles/templates/articles/detail.html
  articles/views.py
  images/images/밍이.jpg
  products/migrations/0001_initial.py
  templates/base.html
Labels: BE, fix

#190 chore : articles app 글 상세페이지에서 사진 모달 기능
  articles/templates/articles/detail.html
Labels: BE, chore

#192 chore : articles app 이미지 업로드 사이즈 및 이미지 모달창 사이즈 수정
  articles/models.py
  articles/templates/articles/detail.html
Labels: BE, chore

#193 chore : articles app 헬짱피드 글 쓸때 빈칸으로 다음페이지 안되는 코드 넣음
  README.md
  articles/templates/articles/create.html
Labels: BE, chore

#194 style : swiper에 묻히는 내브바 오류 수정
  templates/article_base.html
  templates/base.html
Labels: fix, style

#195 fix : 내브바 링크 수정
  templates/base.html
Labels: fix

#197 fix : 문의내용 줄 바꿈
  products/templates/products/detail.html
Labels: fix

#198 fix(products) : 문의 내용 및 답글 text-break
  products/templates/products/detail.html
  static/js/product_inquiries.js
Labels: FE, fix

#199 style : 문의 내역 스타일
  products/templates/products/detail.html
Labels: style

#201 style : article 디테일 회원정보 카드 디자인
  articles/templates/articles/detail.html
Labels: style

#202 style : 내브바 디자인 수정
  templates/article_base.html
  templates/base.html
Labels: style

#204 style : article 인덱스 카드 이미지 뭉개짐 해결
  articles/templates/articles/index.html
  static/images/ck-purple.jpg
Labels: style

#205 style : makers x버튼 위치 수정
  templates/article_base.html
  templates/base.html
Labels: style

#207 feat : 카운트다운
  products/templates/products/index.html
  static/css/style.css
Labels: FE, done

#209 style : article 수정 폼
  articles/templates/articles/update.html
  articles/views.py
Labels: style

#210 style : footer
  templates/article_base.html
  templates/base.html
Labels: style

#211 fix : 장바구니 모달 오류 수정
  products/templates/products/detail.html
Labels: fix

#213 fix : 카테고리 선택시 swiper translate3d 초기화
  products/templates/products/index.html
Labels: fix

#215 fix : 검색결과 링크 수정
  accounts/templates/accounts/profile.html
  articles/templates/articles/search.html
Labels: fix

#216 chore: aritcle detail 미세 수정
  articles/templates/articles/detail.html
Labels: style, chore

#217 fix : 문의 수정 오류
  products/templates/products/detail.html
  products/views.py
Labels: fix
